version: "3"
services:
  front:
    build: .
    restart: unless-stopped
    container_name: tc_front
    ports:
      - "80:3000"
    # Uncomment volumes section for development
    #volumes:
    #  - "./:/app"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: tcdb
